### ISSUE TITLE
ToDo-List

### ISSUE THREAD

**Issue by paul-buerkner** [donaldRwilliams/Meta_Schizophrenia#1]
This issue should help us in keeping track what needs to be done (feel free to add points):
- [x] a single data frame that includes between and within subject data for symptoms
- [x] code moderator variables
- [x] write an R-script containing all data preparation stuff so that (ideally) we end up with one single data frame to be used in all of our analyses
- [x] decide about which effect sizes to use (SMD, SMCR, ...)
- [x] perform the multivariate analysis (symptoms)
- [x] perform additional analysis (symptoms)
  - [x] moderator analysis
  - [x] investigate publication bias
  - [x] leave one out analysis
  - [x] analyse overall symptoms
- [x] Skype conversation to discuss cognitive deficits 
  - [x] Discuss strange results of primary studies (also previous MAs have some inconsistencies) 
  - [x] Determine how to collaborate on the writing portion of the paper
  - [x] Discuss correlations between symptoms
  - [x] Discuss results of analysis 
- [x] Through email, get baseline data for total symptoms from Gibson
- [x] Through email, get medication information from Dagani 
- [x] prepare cognitive deficits data
- [x] skpye conversation to discuss how best to analyze cognitive data
  - [x] Determine whether we will use one effect for each study, or combine effects within studies (or use all of them)
  - [x] discuss subgroup variables
  - [x] should we report both SMD and SMCR or only the latter?
  - [x] how to deal with the 'symptoms' outcomes in the cognitive analysis?
  - [x] is summarizing over all cognitive outcomes reasonable (or should we separate after subgroup 1 directly)?
  - [x] do we need p-values?
  - [x] discuss `admin_int` variable
- [x] analyse cognitive deficits data
  - [x] Main Meta-Analysis
  - [x] Moderator analysis
    - [x] analyse subgroups
    - [x] analyse other moderators
  - [x] investigate publication bias
  - [x] leave-one-out analysis
  - [x] vary the between outcome correlation in a sensitivity analysis
- [x] find journal for the symptoms paper
- [x] get missing symptoms data

**Comment by donaldRwilliams** [comment]
I am a little unclear as to the difference between SMD and SMCR. I thought that the difference was SMCR was for dependent measures ?

**Comment by paul-buerkner** [comment]
Yep thats true. I think we should to both, SMD (for comparison between EG
and CG at post-time) and SMCR (for pre-post comparisons). We should also
think about computing SMCR for both EG and CG and comparing those as
explained here: http://www.metafor-project.org/doku.php/analyses:morris2008

This way, we woul control for both EG vs. CG and pre vs. post at the same
time.

2016-06-02 15:51 GMT+02:00 Donald R. Williams notifications@github.com:

**Comment by donaldRwilliams** [comment]
Should we also have SMCR for the placebo group (for pre-post comparisons) and SMD to compare pre-treatment measures (for comparison between EG and CG at baseline) ?

**Comment by paul-buerkner** [comment]
We should do this, yes. However, I would prefer not analysing SMCR
separately for EG and CG but to combine them via SMCR = SMCR_EG - SMCR_CG
and Var(SMCR) = Var(SMCR_EG) + Var(SMCR_EG).

We would then have SMD for pre and post mainly for comparison with other
meta-analyses, which likely also used SMD and the SMCR as our main effect
size controling for CG as well as for pre-treatment values.

2016-06-02 16:03 GMT+02:00 Donald R. Williams notifications@github.com:

**Comment by donaldRwilliams** [comment]
Sounds good. I will send you the data frame with the raw data so that you can do what you think is best :+1:

**Comment by paul-buerkner** [comment]
Moderator analyses (assuming the same effects across symptom types to have at least some power) are now done. The only moderator that has a significant effect is admin_int for the SMD (hedges g). I don't really want to interpret this, because this is just comparing 2 studies with the other studies. Also, I don't know if we should apply moderator analysis for the SMD at all of if we should focus on the SMCR in this case. What do you think?

**Comment by donaldRwilliams** [comment]
I think our main focus should be on SMCR, mainly because I think it makes the most sense. As such, I agree with you that we should not interpret the moderator effect. Would it makes sense, however, to mention the finding in the discussion, but argue that SMD does not account for baseline scores so is probably not valid? Could this also be used to show that SMCR is more appropriate ? 

I have received the total symptoms from Gibson, so will be sending you the data frame for total symptoms with in the hour.

**Comment by paul-buerkner** [comment]
I have now finished the analysis of the 3 subgroup variables. I think we should gather points to discuss at our next skype call (I see you have already started doing so). In the meantime, I will perform some additional analysis. Did you already find the time to code some other moderators that are worth investigating?

**Comment by donaldRwilliams** [comment]
I am currently working on coding other moderators. I should be finished in no more than two hours.

**Comment by paul-buerkner** [comment]
Since we submitted the first paper and already have a new ToDo list for the secoen one, I think we should close this issue.
