### ISSUE TITLE
To-do list_cogntive

### ISSUE THREAD

**Issue by donaldRwilliams** [donaldRwilliams/Meta_Schizophrenia#3]
- [x] Discuss focus of the paper (general, social, or both)
- [x] Discuss within study effects 
  - [x] Rationale for using all effects reported in paper  
- [x] Discuss timeline for submission
- [x] Individual areas of social cognition
- [x] Separate social from general cognition in the analysis
- [x] Code Goldman et al. 2011
